input:
  path: "/home/ubuntu/workspace/Tiamat/YOLO-World-DINO/DINO_test/dt_scene_based_sdg_data_path_0005"
  type: "directory"

output:
  directory: "inference_results/"
  save_annotated: true
  save_json: true
  results_filename: "results.json"

visualization:
  bbox_thickness: 2
  font_scale: 0.5
  show_confidence: true
  show_class_name: true

client:
  server_url: http://localhost:12182/yolo_world
  batch_size: 4

evaluation:
  iou_thresholds: [0.5, 0.75]
  save_json: true

